-   id: sqlproj-sort
    name: Sorting the files referenced in SSDT-SSDT project
    description: "Sort sqlproj file"
    entry: sqlprojsort
    language: python
    files:  \.(sqlproj)$
-   id: dtproj-sort
    name: Sorting the files referenced in SSDT-SSIS project
    description: "Sort dtproj file"
    entry: dtprojsort
    language: python
    files:  \.(dtproj)$
-   id: bim-sort
    name: Sorting the datasources, tables, relationships etc in Model.bim
    description: "Sort dtproj file"
    entry: bimsort
    language: python
    files:  \.(bim)$
