-   id: sqlproj-sort
    name: Fixing the order of files referenced in SSDT-SSDT project
    description: "Sort sqlproj file"
    entry: sqlprojsort
    language: python
    files:  \.(sqlproj)$
-   id: dtproj-sort
    name: Fixing the order of files referenced in SSDT-SSIS project
    description: "Sort dtproj file"
    entry: dtprojsort
    language: python
    files:  \.(dtproj)$
